name: Deploy Links Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_links_lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./links
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        env:
          LINKS_FUNCTION_URL: ${{ vars.LINKS_FUNCTION_URL }}
        run: |
          npx esbuild index.ts --bundle --outdir=dist --platform=node --minify
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=$LINKS_FUNCTION_URL --zip-file=fileb://deploy.zip
